name: Schedule Slack Message

on:
  schedule:
    - cron: "0 0 28-31 * *" # 매월 28, 29, 30, 31일에 실행
    - cron: "0 0 1 * *" # 매월 1일에 실행하여 마지막 날인지 확인

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X POST https://gaebal-bot.vercel.app/api/send-message
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
