name: Schedule Slack Message

on:
  schedule:
    - cron: "*/1 * * * *" # 1분마다 실행

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X POST https://gaebal-bot.vercel.app/api/send-message
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
